/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

@SuppressWarnings("doclint:missing") // javadoc生成時の警告を抑止
public class HelloJitPack2 {
    private String message = "Hello JitPack!";

    public String getMessage() {
        return message;
    }
}
