/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloJitPackTests {
    @Test
    void someLibraryMethodReturnsTrue() {
        HelloJitPack2 hello = new HelloJitPack2();
        assertEquals("Hello JitPack!", hello.getMessage());
    }
}
